export default {
    MARK_NOTIFICATION_HAS_READED_BY_ID:'MARK_NOTIFICATION_HAS_READED_BY_ID',
    MARK_ALL_NOTIFICATION_HAS_READED:'MARK_ALL_NOTIFICATION_HAS_READED',
    START_MARK_NOTIFICATION_HAS_READED:'START_MARK_NOTIFICATION_HAS_READED',
    FINISH_MARK_NOTIFICATION_HAS_READED:'FINISH_MARK_NOTIFICATION_HAS_READED',
    RECIVED_NOTIFICATION:'RECIVED_NOTIFICATION'
}